// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHcv11AlWibt19d_dYPq-hoZfya7RaDfw',
    appId: '1:91817906532:web:7f72683324311ccc4f6a71',
    messagingSenderId: '91817906532',
    projectId: 'sporify01',
    authDomain: 'sporify01.firebaseapp.com',
    storageBucket: 'sporify01.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL0tvKposHs4RwhsPdZ6x9Iq7wIuvghLA',
    appId: '1:91817906532:android:14a561a52cc61acb4f6a71',
    messagingSenderId: '91817906532',
    projectId: 'sporify01',
    storageBucket: 'sporify01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGJsQd9eVo2zfGWTrO93b4bECJGzELpK4',
    appId: '1:91817906532:ios:483b4f2f7a90207a4f6a71',
    messagingSenderId: '91817906532',
    projectId: 'sporify01',
    storageBucket: 'sporify01.firebasestorage.app',
    iosBundleId: 'com.example.sporify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGJsQd9eVo2zfGWTrO93b4bECJGzELpK4',
    appId: '1:91817906532:ios:483b4f2f7a90207a4f6a71',
    messagingSenderId: '91817906532',
    projectId: 'sporify01',
    storageBucket: 'sporify01.firebasestorage.app',
    iosBundleId: 'com.example.sporify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHcv11AlWibt19d_dYPq-hoZfya7RaDfw',
    appId: '1:91817906532:web:f61aa80354f38b404f6a71',
    messagingSenderId: '91817906532',
    projectId: 'sporify01',
    authDomain: 'sporify01.firebaseapp.com',
    storageBucket: 'sporify01.firebasestorage.app',
  );
}
